apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-data-jpa-app-deployment
  labels:
    app: hello-spring-data-jpa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-data-jpa-app
  template:
    metadata:
      labels:
        app: hello-spring-data-jpa-app
    spec:
      containers:
      - name: app
        image: hello-spring-data-jpa:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
