apiVersion: v1
kind: Service
metadata:
  name: hello-spring-data-jpa-db-svc
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: hello-spring-data-jpa-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-spring-data-jpa-db-ss
spec:
  selector:
    matchLabels:
      app: hello-spring-data-jpa-postgres
  serviceName: hello-spring-data-jpa-db-svc
  template:
    metadata:
      labels:
        app: hello-spring-data-jpa-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15.1
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB 
          value: test_db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100M

